Randomized Terrain Layers
CzechPMDevs/MultiWorld pull request #144
Opened 2021-06-06 13:32 UTC by DerCooleVonDem

Just some little edits on the GroundCover.php Populator that it is able to generate randomized terrain layers. 

I created this populator so that I can generate random terrain layers in my MultiWorld fork. I think you can use this in the future or it is an inspiration/idea :)

2021-06-07 19:41 UTC, VixikHD requested changes
Have you tested it?

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/NormalGenerator.php
> +
Leave only one line

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/NormalGenerator.php
> +        //edit the GroundCover Populator that it be able to generate randomized terrain :) (Could be useful in future)
This comment will be useless in the future

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
> +        //EXAMPLE POPULATION
Useless comment

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
> +            ["{$sand}:0", "{$gravel}:0"],
Don't use strings to pass item ids, use array or any other better way

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/populator/impl/GroundCoverCustom.php
> +
1 line is enough

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/populator/impl/GroundCoverCustom.php
> +
Missing implemented functions

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
>          $this->setGroundCover([
Why is it changed only in River biome?

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
> +        $gravel = Block::GRAVEL;
Useless definitions

2021-06-07 19:41 UTC, VixikHD commented on src/czechpmdevs/multiworld/generator/normal/populator/impl/GroundCoverCustom.php
> +                            $data = explode(":",(string)$randContent);
Don't use strings to pass blocks

2021-06-12 06:13 UTC, DerCooleVonDem commented
> Have you tested it?

Yes ive tested it and it works as intended

2021-06-12 06:41 UTC, DerCooleVonDem commented
I now change everything like you want it to

2021-06-12 07:05 UTC, DerCooleVonDem commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
>          $this->setGroundCover([
Its a example to show you my idea

2021-06-12 07:05 UTC, DerCooleVonDem commented on src/czechpmdevs/multiworld/generator/normal/biome/River.php
>          $this->setGroundCover([
will be changed as soon as possible

2021-06-29 22:51 UTC, benda95280 commented
Any news ? :)

2021-08-21 22:57 UTC, closed without merging